### ISSUE TITLE
Prev/Next links

### ISSUE THREAD

**Issue by ahmedzein** [ahmedzein/portfolio#15]
when I click on the previous/next button I get a 404 page.

http://ahmedzein.github.io/portfolio/portfolio-page-two/

![screen shot 2015-11-25 at 7 46 11 pm](https://cloud.githubusercontent.com/assets/6373204/11412637/3f198270-93ad-11e5-80c3-3750bc47cd0b.png)

**Comment by thomasjbradley** [comment]
Maybe try adding `{{site.baseurl}}/` in front of the two links, in the `href` attributes.

To tag me in an issue all you have to do is write `@thomasjbradley` in the description.
